ipfs-cap cancel

diff --git a/ipfs-cap b/ipfs-cap
--- a/ipfs-cap
+++ b/ipfs-cap
@@ -48,6 +48,9 @@ fi
 
 log "capturing screen..."
 img=$(screencap | ipfs add -q)
+if [ $? -eq 0 ]; then
+  die "failed to take screenshot"
+fi
 log " $img\n"
 
 
